### ISSUE TITLE
The 'ThreadPool' module

### ISSUE THREAD

**Issue by SZUHvern** [funnyzhou/REFERS#3]
Dear author,

I encounter an undefined problem when using 'pool = ThreadPool(64)' in mimic_resize_image.ipynb.
I have tried to import pakage of 'Threading', 'Multithreading' and  'concurrent.futures', but both of them seem didn't have the pakage of 'Threading' also.
Could you please help me to solve this problems?

Many thanks

**Comment by funnyzhou** [comment]
Perhaps you need to do so:

from multiprocessing.pool import ThreadPool

Best,
