### ISSUE TITLE
Missing MIMIC-CXR-JPG‘s 'caption_patients.txt'

### ISSUE THREAD

**Issue by SZUHvern** [funnyzhou/REFERS#4]
Thanks for sharing the code!
However, after downloading MIMIC-CXR-JPG and rearranging the data according to 'read me', I found that the file 'XX_img_caption_patients.txt' was still missing when performing pretrain_refers.py.

Could you please check it for me? 
Many thanks!

**Comment by funnyzhou** [comment]
Thanks for your reminder.

I've uploaded the missing two files to Google Drive. You can refer to README for the link.

**Comment by SZUHvern** [comment]
Thanks a lot,

With the adoption of 'img_caption_patients.txt' file, I found that there is still missing 'VIT-B_16. npz'
There are many versions of the weight of VIT-16, including 'torchvision.models.vit_b_16', but I cannot make sure which one you use.

Do you mind uploading the weight as well, or telling where the link is.

Thanks!

**Comment by funnyzhou** [comment]
This model has been uploaded.
